apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-database
  title: Create Database
  description: Create a Database Custom Resource
spec:
  owner: platform-team
  type: resource

  parameters:
    - title: Database Metadata
      required:
        - name
        - namespace
      properties:
        name:
          title: Database name
          type: string
        namespace:
          title: Kubernetes namespace
          type: string
          default: default

    - title: Database Configuration
      required:
        - engine
        - size
      properties:
        engine:
          title: Engine
          type: string
          enum:
            - postgres
            - mysql
        size:
          title: Size
          type: string
          enum:
            - small
            - medium
            - large
        storageGB:
          title: Storage (GB)
          type: number
          minimum: 10
          maximum: 1024
          default: 50
        backup:
          title: Enable backup
          type: boolean
          default: true

  steps:
    - id: render
      name: Render Database CR
      action: fetch:template
      input:
        targetPath: .
        templateFile: database.yaml
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          engine: ${{ parameters.engine }}
          size: ${{ parameters.size }}
          storageGB: ${{ parameters.storageGB }}
          backup: ${{ parameters.backup }}

    - id: apply
      name: Apply Database CR
      action: kubernetes:apply
      input:
        manifestPath: database.yaml
        namespace: ${{ parameters.namespace }}