apiVersion: arubacloud.com/v1alpha1
kind: Project
metadata:
  name: test-nuovo-progetto
  namespace: tenant-aru-2976467
spec:
  tenant: ARU-2976467
  description: test-nuovo-progetto
  tags: []
  default: false
