apiVersion: arubacloud.com/v1alpha1
kind: Project
metadata:
  name: test-devopsitaly
  namespace: tenant-aru-297647
spec:
  tenant: ARU-297647
  description: devopsitaly
  tags: []
  default: false
