apiVersion: arubacloud.com/v1alpha1
kind: BlockStorage
metadata:
  name: test-bs-4
  namespace: tenant-aru-297647
spec:
  tenant: ARU-297647
  tags: []
  location:
    value: ITBG-Bergamo
  sizeGb: 20
  billingPeriod: Hour
  dataCenter: ITBG-1
  bootable: true
  image: LU24-001
  projectReference:
    name: test-nuovo-progetto
    namespace: tenant-aru-297647
