apiVersion: arubacloud.com/v1alpha1
kind: BlockStorage
metadata:
  name: test-mio-blockstorage
  namespace: tenant-aru-297647
spec:
  tenant: ARU-297647
  tags: []
  location:
    value: ITBG-Bergamo
  sizeGb: 19
  billingPeriod: Hour
  dataCenter: ITBG-2
  bootable: false
  projectReference:
    name: test-progetto-nuovo
    namespace: tenant-aru-297647
