apiVersion: arubacloud.com/v1alpha1
kind: Project
metadata:
  name: nuovo-prog
  namespace: tenant-aru-297647
spec:
  tenant: ARU-297647
  description: nuovo-prog
  tags: []
  default: false
