apiVersion: arubacloud.com/v1alpha1
kind: ElasticIp
metadata:
  name: test-mio-elastic-ip
  namespace: ARU-297647
spec:
  tenant: ARU-297647
  tags: []
  location:
    value: ITBG-Bergamo
  billingPlan:
    billingPeriod: Hour
  projectReference:
    name: test-mio-project
    namespace: ARU-297647
