# External Secrets Operator
# Synchronizes secrets from external secret management systems (like Vault) to Kubernetes
# Deploys after vault-config to use the AppRole credentials for Vault integration

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"  # Deploy after vault-config (wave 5), before arubacloud-operator (wave 10)
spec:
  project: platform
  
  # Source: External Secrets Operator Helm chart
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.11
    helm:
      values: |
        installCRDs: true
        
        # Enable webhook for validation
        webhook:
          port: 9443
        
        # Resources for the operator
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
        
        # ServiceMonitor for Prometheus (if available)
        serviceMonitor:
          enabled: false
        
        # Global configuration
        global:
          # Compatibility options
          compatibility:
            openshift:
              adaptSecurityContext: auto
  
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
