# Backstage Developer Portal
# This deploys Backstage to provide a developer portal for managing
# Kubernetes resources including ArubaCloud custom resources via the catalog
# Prerequisites: Kubernetes cluster with CRDs installed

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"  # Deploy after operators (wave 10)
spec:
  project: platform
  
  source:
    repoURL: https://backstage.github.io/charts
    chart: backstage
    targetRevision: 1.8.2
    helm:
      values: |
        backstage:
          # Using official Backstage image
          # Note: For production, build a custom image with your configuration
          image:
            registry: ghcr.io
            repository: backstage/backstage
            tag: latest
          
          # Extra environment variables for runtime configuration
          extraEnvVars:
            - name: APP_CONFIG_app_baseUrl
              value: "http://localhost:7007"
            - name: APP_CONFIG_backend_baseUrl  
              value: "http://localhost:7007"
            - name: LOG_LEVEL
              value: "debug"
          
          # Application configuration
          appConfig:
            app:
              title: DevOps Italy 2026 Portal
              baseUrl: http://localhost:7007
            
            backend:
              baseUrl: http://localhost:7007
              listen:
                port: 7007
                host: 0.0.0.0
              cors:
                origin: http://localhost:7007
                credentials: true
              # Allow backend to read from these hosts (e.g. catalog template URLs)
              reading:
                allow:
                  - host: raw.githubusercontent.com
                  - host: github.com
              # Allow unauthenticated API access so guest can load catalog (dev/internal only)
              auth:
                dangerouslyDisableDefaultAuthPolicy: true
              # Kubernetes plugin configuration
              csp:
                connect-src: ["'self'", 'http:', 'https:']
              
              database:
                client: better-sqlite3
                connection: ':memory:'
            
            # Auth: enable guest provider so "Sign in as guest" works without fallback prompt
            auth:
              environment: development
              providers:
                guest: {}
            
            # GitHub integration for catalog
                  # For private repos, add: token: ${GITHUB_TOKEN}

            integrations:
              github:
                - host: github.com
                  # For public repos, no token needed
                  # For private repos, add: token: ${GITHUB_TOKEN}
                # Workaround: parseRepoUrl in publish:github:pull-request sometimes resolves host as "https"
                - host: https
                  apiBaseUrl: https://api.github.com
                  rawBaseUrl: https://raw.githubusercontent.com
                  # If repo is private, add: token: ${GITHUB_TOKEN}

            # Enable Kubernetes plugin
            kubernetes:
              serviceLocatorMethod:
                type: multiTenant
              clusterLocatorMethods:
                - type: config
                  clusters:
                    - url: https://kubernetes.default.svc
                      name: local-cluster
                      authProvider: serviceAccount
                      skipTLSVerify: false
                      skipMetricsLookup: false
            
            # Catalog configuration
            catalog:
              import:
                entityFilename: catalog-info.yaml
              rules:
                - allow: [Component, System, API, Resource, Location, Template]
              locations:
                # Example entities from Backstage
                - type: url
                  target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml
                # ArubaCloud Project template (raw URL so Backstage can load the template YAML)
                - type: url
                  target: https://raw.githubusercontent.com/Arubacloud/devops-italy-2026/main/others/backstage/templates/arubacloud-project/template.yaml
        
        # Service Account for Kubernetes API access
        serviceAccount:
          create: false
          name: backstage
        
        # Service configuration
        service:
          type: ClusterIP
          ports:
            backend: 7007
        
        # Ingress configuration (disabled by default)
        ingress:
          enabled: false
        
        # PostgreSQL (using in-memory SQLite for simplicity, use PostgreSQL for production)
        postgresql:
          enabled: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m