apiVersion: arubacloud.com/v1alpha1
kind: Project
metadata:
  name: test-mio-project
  namespace: ARU-297647
spec:
  tenant: ARU-297647
  description: test-mio-project
  tags: []
  default: false
