apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: arubacloud-project
  title: Create ArubaCloud Project
  description: Generates a Project CR (arubacloud.com/v1alpha1). Copy the YAML from the result and add it to your GitOps repo or apply with kubectl.
spec:
  owner: platform-team
  type: service
  lifecycle: experimental

  parameters:
    - title: Project details
      required:
        - name
        - namespace
        - tenant
      properties:
        name:
          title: Name
          description: Project name (metadata.name)
          type: string
          ui:autofocus: true
        namespace:
          title: Namespace
          description: Target Kubernetes namespace
          type: string
          default: default
        tenant:
          title: Tenant
          description: Tenant identifier for the project
          type: string
        description:
          title: Description
          description: Optional project description
          type: string
          default: ""
        tags:
          title: Tags
          description: Optional list of tags
          type: array
          items:
            type: string
          default: []
        default:
          title: Default project
          description: Whether this is the default project
          type: boolean
          default: false

  steps:
    - id: fetch-skeleton
      name: Generate Project CR YAML
      action: fetch:template
      input:
        url: https://github.com/Arubacloud/devops-italy-2026/tree/main/others/backstage/gitops-skeleton
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          tenant: ${{ parameters.tenant }}
          description: ${{ parameters.description }}
          tags: ${{ parameters.tags }}
          default: ${{ parameters.default }}

  output:
    text: |
      Copy the YAML below into your GitOps repo (e.g. argocd/applications/arubacloud-projects/${{ parameters.tenant }}-project-${{ parameters.name }}.yaml) and open a PR, or apply with: kubectl apply -f -

      apiVersion: arubacloud.com/v1alpha1
      kind: Project
      metadata:
        name: ${{ parameters.name }}
        namespace: ${{ parameters.namespace }}
      spec:
        tenant: ${{ parameters.tenant }}
        description: ${{ parameters.description }}
        tags: ${{ parameters.tags }}
        default: ${{ parameters.default }}
      