apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: arubacloud-project
  title: Create ArubaCloud Project
  description: Crea un Progetto ArubaCloud. Se è il primo progetto del tenant, crea anche l'Application Argo CD.
spec:
  owner: platform-team
  type: service
  lifecycle: experimental

  parameters:
    - title: Project details
      required: [name, tenant, githubToken]
      properties:
        name:
          title: Name
          type: string
        tenant:
          title: Tenant ID
          type: string
          description: "Esempio: ARU-297647"
        githubToken:
          title: GitHub token
          type: string
          ui:widget: password

  steps:
    # 1. Genera il file del Progetto (unico per ogni esecuzione)
    - id: fetch-project-cr
      name: Generate Project CR
      action: fetch:template
      input:
        url: https://github.com/Arubacloud/devops-italy-2026/tree/main/others/backstage/gitops-skeleton-project
        targetPath: ./argocd/applications/${{ parameters.tenant }}
        token: ${{ parameters.githubToken }}
        values:
          name: ${{ parameters.name }}
          tenant: ${{ parameters.tenant }}

    # 2. Genera l'App-of-Apps del Tenant (Idempotente)
    # Se il file esiste già nel repo principale, la PR di Backstage caricherà la stessa versione.
    # Se non esiste, verrà aggiunto.
    - id: fetch-argo-app
      name: Ensure Tenant Application exists
      action: fetch:template
      input:
        url: https://github.com/Arubacloud/devops-italy-2026/tree/main/others/backstage/templates/argo-app-template
        targetPath: ./argocd/tenants
        token: ${{ parameters.githubToken }}
        values:
          tenant: ${{ parameters.tenant }}

    # 3. Pubblica la PR
    - id: create-pr
      name: Open PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=Arubacloud&repo=devops-italy-2026
        branchName: project-${{ parameters.tenant }}-${{ parameters.name }}
        token: ${{ parameters.githubToken }}
        title: "feat: add project ${{ parameters.name }} to tenant ${{ parameters.tenant }}"
        description: |
          Aggiunta del progetto ArubaCloud. 
          Se questo è il primo progetto del tenant, è stata generata anche l'Application Argo CD in argocd/tenants/${{ parameters.tenant }}.yaml.
        sourcePath: ./
        targetPath: .