# ArubaCloud Project Template
# Creates a Project custom resource in Kubernetes

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: arubacloud-project
  title: ArubaCloud Project
  description: Create a new ArubaCloud Project resource
  tags:
    - arubacloud
    - project
    - kubernetes
spec:
  owner: platform-team
  type: resource
  
  parameters:
    - title: Project Information
      required:
        - name
        - namespace
        - tenant
      properties:
        name:
          title: Project Name
          type: string
          description: Name of the project
          ui:autofocus: true
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
          ui:help: 'Lowercase alphanumeric characters or hyphens'
        
        namespace:
          title: Namespace
          type: string
          description: Kubernetes namespace for the project
          default: default
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
        
        tenant:
          title: Tenant
          type: string
          description: ArubaCloud tenant identifier
          ui:help: 'The tenant that will own this project'
        
        description:
          title: Description
          type: string
          description: Project description
          default: ''
          ui:widget: textarea
          ui:options:
            rows: 3
        
        tags:
          title: Tags
          type: array
          description: Tags for the project
          default: []
          items:
            type: string
          ui:options:
            orderable: true
        
        default:
          title: Default Project
          type: boolean
          description: Set this as the default project
          default: false

  steps:
    - id: fetch-template
      name: Fetch Kubernetes Manifest Template
      action: fetch:template
      input:
        url: ./templates/project
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          tenant: ${{ parameters.tenant }}
          description: ${{ parameters.description }}
          tags: ${{ parameters.tags }}
          default: ${{ parameters.default }}

    - id: log-manifest
      name: Log Generated Manifest
      action: debug:log
      input:
        message: |
          Creating ArubaCloud Project:
          Name: ${{ parameters.name }}
          Namespace: ${{ parameters.namespace }}
          Tenant: ${{ parameters.tenant }}
    
    - id: apply-manifest
      name: Apply to Kubernetes
      action: kubernetes:apply
      input:
        manifest: |
          apiVersion: arubacloud.com/v1alpha1
          kind: Project
          metadata:
            name: ${{ parameters.name }}
            namespace: ${{ parameters.namespace }}
          spec:
            tenant: ${{ parameters.tenant }}
            description: ${{ parameters.description }}
            tags: ${{ parameters.tags | dump }}
            default: ${{ parameters.default }}

  output:
    links:
      - title: View in Kubernetes
        url: https://kubernetes.default.svc/apis/arubacloud.com/v1alpha1/namespaces/${{ parameters.namespace }}/projects/${{ parameters.name }}
    text:
      - title: Project Created
        content: |
          Successfully created ArubaCloud Project: ${{ parameters.name }}
          Namespace: ${{ parameters.namespace }}
          Tenant: ${{ parameters.tenant }}
